name: braincloud_data_persistence
description: "brainCloud helper package. brainCloud_dart_peristence provide a persistence support into the platform preferences"
version: 5.5.0+1
homepage: https://getbraincloud.com/

environment:
  sdk: ^3.6.0
  flutter: '>=3.27.0'

# Add regular dependencies here.
dependencies:
  braincloud: ^5.5.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
